l05_flask_migrations_tests_js/accounts/models.py
from flask_login import UserMixin

from database import db


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True, nullable=False)
    hashed_password = db.Column(db.String(80), unique=False, nullable=False)

    def __repr__(self):
        return f"<User {self.username}>"

l05_flask_migrations_tests_js/company_management/models.py
from database import db


class Department(db.Model):
    __tablename__ = "departments"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True, nullable=False)
    employees = db.relationship('Employee')

    def __repr__(self):
        return f"<Department {self.name}>"


class Employee(db.Model):
    __tablename__ = "employees"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    surname = db.Column(db.String(64), nullable=False)
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    department = db.relationship('Department', back_populates='employees')

    def __repr__(self):
        return f"<Employee {self.name}>"

l05_flask_migrations_tests_js/company_management/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class DepartmentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])


class EmployeeForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])
    surname = StringField('Surname', validators=[DataRequired(), Length(min=1, max=64)])
    department_name = StringField('department_name', validators=[DataRequired()])

l05_flask_migrations_tests_js/accounts/controllers.py
from flask import request, redirect, url_for, flash, render_template, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user

from accounts.services import find_by_username_and_password, IncorrectPasswordError, NotFoundError, find_user_by_id

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        remember_me = len(request.form.getlist('remember_me')) > 0
        try:
            user = find_by_username_and_password(username, password)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            return redirect(url_for('accounts.login'))
        else:
            login_user(user, remember=remember_me)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/login.html')


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('company_management.main_page'))


@accounts_blueprint.route("/user/<int:user_id>", methods=["GET"])
@login_required
def user_info(user_id: int):
    try:
        user = find_user_by_id(user_id)
        return render_template('accounts/user_info.html', user=user)
    except NotFoundError:
        abort(404)


@accounts_blueprint.route("/user", methods=["GET"])
@login_required
def current_user_info():
    return render_template('accounts/user_info.html', user=current_user)

l05_flask_migrations_tests_js/app.py
import os

from flask import Flask

from accounts.controllers import accounts_blueprint
from accounts.login_manager import login_manager
# noinspection PyUnresolvedReferences
from accounts.models import User
from company_management.controllers import company_management_blueprint
# noinspection PyUnresolvedReferences
from company_management.models import Department, Employee
from database import db, migrate
from error_handlers import page_not_found
from local_configs import Configuration

app = Flask(__name__)

if not os.getenv('IS_PRODUCTION', None):
    app.config.from_object(Configuration)

db.init_app(app)
migrate.init_app(app, db)
login_manager.init_app(app)

app.register_blueprint(accounts_blueprint, url_prefix='/accounts')
app.register_blueprint(company_management_blueprint, url_prefix='/')
app.register_error_handler(404, page_not_found)


if __name__ == '__main__':
    app.run(debug=True)

l05_flask_migrations_tests_js/company_management/__init__.py
from flask import Blueprint

company_management_blueprint = Blueprint('company_management', __name__)

l05_flask_migrations_tests_js/company_management/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify

from company_management.forms import DepartmentForm, EmployeeForm
from company_management.services import get_paginated_departments_list, create_department, DatabaseError, \
    get_department_by_name_part, create_employee

company_management_blueprint = Blueprint('company_management', __name__, template_folder='templates')


@company_management_blueprint.route('/', methods=('GET',))
def main_page():
    return render_template('company_management/main_page.html')


@company_management_blueprint.route('/departments', methods=('GET',))
def departments_list():
    raw_page = request.args.get('page', '1')
    page = int(raw_page) if raw_page.isdigit() else 1
    departments_pagination = get_paginated_departments_list(page)
    return render_template('company_management/departments_list.html', departments_pagination=departments_pagination)


@company_management_blueprint.route('/departments/create', methods=('GET', 'POST'))
def create_department_page():
    form = DepartmentForm()
    if form.validate_on_submit():
        try:
            create_department(form)
        except DatabaseError as e:
            flash(str(e))
        else:
            flash('Successfully created new department')
            return redirect(url_for('company_management.departments_list'))
        return redirect(url_for('company_management.create_department_page'))
    return render_template('company_management/create_department.html', form=form)


@company_management_blueprint.route('/employees/search', methods=('POST',))
def search_department_by_name():
    json_content = request.get_json()
    result = get_department_by_name_part(json_content['name'])
    return jsonify([{'id': d.id, 'name': d.name} for d in result])


@company_management_blueprint.route('/employees/create', methods=('GET', 'POST'))
def create_employee_page():
    form = EmployeeForm()
    if form.validate_on_submit():
        try:
            create_employee(form)
        except DatabaseError as e:
            flash(str(e))
        else:
            flash('Successfully created new employee')
            return redirect(url_for('company_management.main_page'))
        return render_template('company_management/create_employee.html', form=form)
    return render_template('company_management/create_employee.html', form=form)

l05_flask_migrations_tests_js/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %} - ITIS</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
<nav>
    <h1><a href="{{ url_for('company_management.main_page') }}">ITIS</a></h1>
    <ul>
        <li><a href="{{ url_for('company_management.departments_list') }}">Departments list</a></li>
        {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('accounts.current_user_info') }}">{{ current_user.username }}</a></li>
            <li><a href="{{ url_for('accounts.logout') }}">Log Out</a></li>
        {% else %}
            <li><a href="{{ url_for('accounts.login') }}">Log In</a></li>
        {% endif %}
    </ul>
</nav>
<section class="content">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    <div class="main_content">
        {% block content %}{% endblock %}
    </div>
</section>
</body>
</html>

l05_flask_migrations_tests_js/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
    <div class=pagination>
        {%- for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <a href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                {% else %}
                    <strong>{{ page }}</strong>
                {% endif %}
            {% else %}
                <span class=ellipsis>…</span>
            {% endif %}
        {%- endfor %}
    </div>
{% endmacro %}