l05_flask_migrations_tests_js/company_management/models.py
from database import db


class Department(db.Model):
    __tablename__ = "departments"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True, nullable=False)
    employees = db.relationship('Employee')

    def __repr__(self):
        return f"<Department {self.name}>"


class Employee(db.Model):
    __tablename__ = "employees"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    surname = db.Column(db.String(64), nullable=False)
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    department = db.relationship('Department', back_populates='employees')

    def __repr__(self):
        return f"<Employee {self.name}>"

l05_flask_migrations_tests_js/company_management/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class DepartmentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])


class EmployeeForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=1, max=64)])
    surname = StringField('Surname', validators=[DataRequired(), Length(min=1, max=64)])
    department_name = StringField('department_name', validators=[DataRequired()])

l05_flask_migrations_tests_js/company_management/__init__.py
from flask import Blueprint

company_management_blueprint = Blueprint('company_management', __name__)

l05_flask_migrations_tests_js/company_management/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify

from company_management.forms import DepartmentForm, EmployeeForm
from company_management.services import get_paginated_departments_list, create_department, DatabaseError, \
    get_department_by_name_part, create_employee

company_management_blueprint = Blueprint('company_management', __name__, template_folder='templates')


@company_management_blueprint.route('/', methods=('GET',))
def main_page():
    return render_template('company_management/main_page.html')


@company_management_blueprint.route('/departments', methods=('GET',))
def departments_list():
    raw_page = request.args.get('page', '1')
    page = int(raw_page) if raw_page.isdigit() else 1
    departments_pagination = get_paginated_departments_list(page)
    return render_template('company_management/departments_list.html', departments_pagination=departments_pagination)


@company_management_blueprint.route('/departments/create', methods=('GET', 'POST'))
def create_department_page():
    form = DepartmentForm()
    if form.validate_on_submit():
        try:
            create_department(form)
        except DatabaseError as e:
            flash(str(e))
        else:
            flash('Successfully created new department')
            return redirect(url_for('company_management.departments_list'))
        return redirect(url_for('company_management.create_department_page'))
    return render_template('company_management/create_department.html', form=form)


@company_management_blueprint.route('/employees/search', methods=('POST',))
def search_department_by_name():
    json_content = request.get_json()
    result = get_department_by_name_part(json_content['name'])
    return jsonify([{'id': d.id, 'name': d.name} for d in result])


@company_management_blueprint.route('/employees/create', methods=('GET', 'POST'))
def create_employee_page():
    form = EmployeeForm()
    if form.validate_on_submit():
        try:
            create_employee(form)
        except DatabaseError as e:
            flash(str(e))
        else:
            flash('Successfully created new employee')
            return redirect(url_for('company_management.main_page'))
        return render_template('company_management/create_employee.html', form=form)
    return render_template('company_management/create_employee.html', form=form)

l05_flask_migrations_tests_js/company_management/templates/company_management/create_department.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Create department{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ form.name.label }} {{ form.name() }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

l05_flask_migrations_tests_js/company_management/templates/company_management/create_employee.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Create employee{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ form.name.label }} {{ form.name() }}
        {{ form.surname.label }} {{ form.surname() }}
        <label for="departments-input">Department</label>
        <input type="text" id="departments-input" list="departments-datalist" name="department_name"
               placeholder="Enter department name..." required/>
        <datalist id="departments-datalist"></datalist>
        <input type="submit" value="Create">
    </form>
    <script>
        window.onload = function () {
            const departmentInputElement = document.getElementById('departments-input');
            const departmentDatalistElement = document.getElementById('departments-datalist');

            departmentInputElement.addEventListener('keyup', async function (e) {
                const rawResponse = await fetch('{{ url_for('company_management.search_department_by_name') }}', {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    method: "POST",
                    body: JSON.stringify({"name": departmentInputElement.value})
                })
                const content = await rawResponse.json();
                departmentDatalistElement.innerHTML = "";
                content.forEach((item) => {
                    const option = document.createElement('option');
                    option.value = item.name;
                    departmentDatalistElement.appendChild(option);
                })
            });
        };
    </script>
{% endblock %}

l05_flask_migrations_tests_js/company_management/templates/company_management/departments_list.html
{% extends 'base.html' %}
{% from 'macros.html' import render_pagination with context %}

{% block header %}
    <h1>{% block title %}Departments list{% endblock %}</h1>
{% endblock %}

{% block content %}
    <a href="{{ url_for('company_management.create_department_page') }}">Create new department</a>
    <ul>
        {% for dep in departments_pagination.items %}
            <li>{{ dep.name }}</li>
        {% else %}
            <li>No departments</li>
        {% endfor %}
    </ul>
    {{ render_pagination(pagination=departments_pagination, endpoint='company_management.departments_list') }}
{% endblock %}

l05_flask_migrations_tests_js/company_management/templates/company_management/main_page.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Main page{% endblock %}</h1>
{% endblock %}

{% block content %}
    Main page content
{% endblock %}